// clientes/livros-next/pages/LivroLista.tsx
import React, { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Menu from "../components/Menu";
import Livro from "@/classes/modelo/Livros";
import LinhaLivro from "@/components/LinhaLivro";
import ControleLivros from "../classes/controle/ControleLivros";

const LivroLista: React.FC = () => {
  const [livros, setLivros] = useState<Livro[]>([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    const carregarLivros = async () => {
      const controleLivros = new ControleLivros();
      const livros = await controleLivros.obterLivros();
      setLivros(livros);
      setCarregado(true);
    };

    carregarLivros();
  }, []);

  const excluir = async (codigo: string) => {
    const controleLivros = new ControleLivros();
    await controleLivros
      .excluir(codigo)
      .then(() => {
        setCarregado(false);
      })
      .catch((error) => {
        console.error(error);
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Loja Next - Lista de Livros</title>
      </Head>
      <div></div>
      <Menu />
      <main className="container">
        <h1>Catálogo de Livros</h1>

        <table className="table table-striped">
          <thead className="table-dark">
            <tr>
              <th>Título</th>
              <th>Resumo</th>
              <th>Editora</th>
              <th>Autores</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((livro, index) => (
              <LinhaLivro
                key={index.toString()}
                livro={livro}
                codigo={livro._id ?? ""}
                excluir={() => excluir(livro._id ? livro._id.toString() : "")}
              />
            ))}
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default LivroLista;

// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleLivrosService } from '../controle-livros.service';
import { ControleEditoraService } from '../controle-editora.service';
import { Livro } from '../livro';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css'],
})
export class LivroListaComponent implements OnInit {
  livros: Livro[] = [];

  constructor(
    private controleEditoraService: ControleEditoraService,
    private controleLivrosService: ControleLivrosService
  ) {}

  ngOnInit(): void {
    this.controleLivrosService.obterLivros().then((livros) => {
      this.livros = livros;
    });
  }

  excluir(codigo: string): void {
    this.controleLivrosService.excluir(codigo).then(() => {
      this.controleLivrosService.obterLivros().then((livros) => {
        this.livros = livros;
      });
    });
  }
  obterNome = (codEditora: number): string => {
    return this.controleEditoraService.getNomeEditora(codEditora);
  };
}

<main class="container">
    <h1>Catálogo de Livros</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros">
                <td class="d-flex flex-column align-items-start text-left">{{ livro.titulo }}
                    <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
                </td>
                <td class="col-6 text-left">{{ livro.resumo }}</td>
                <td class="text-left">{{ obterNome(livro.codEditora) }}</td>
                <td class="text-left">
                    <ul class="list-group">
                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>

            </tr>
        </tbody>
    </table>
</main>
