// clientes/livros-react/src/LivroDados.js
import React, { useState } from "react";
import { useNavigate } from 'react-router-dom';
import ControleLivros from "../src/controle/ControleLivros";


function LivroDados() {
    const [titulo, setTitulo] = useState("");
    const [resumo, setResumo] = useState("");
    const [codEditora, setCodEditora] = useState("");
    const [autores, setAutores] = useState("");
    const navigate = useNavigate();

    const incluir = async () => {
        const livro = {
            _id: "",
            titulo: titulo,
            resumo: resumo,
            codEditora: codEditora,
            autores: autores.split(","),
        };

        const controleLivros = new ControleLivros();
        await controleLivros.incluir(livro).then(() => {
            navigate("/");
        });
    };

    return (
        <div className="container">
            <h1>Cadastro de Livro</h1>
            <div className="mb-3">
                <label className="form-label">Título</label>
                <input
                    type="text"
                    className="form-control"
                    id="titulo"
                    value={titulo}
                    onChange={(e) => setTitulo(e.target.value)}
                />
            </div>
            <div className="mb-3">
                <label className="form-label">Resumo</label>
                <textarea
                    className="form-control"
                    id="resumo"
                    value={resumo}
                    onChange={(e) => setResumo(e.target.value)}
                />
            </div>
            <div className="mb-3 d-flex flex-column align-items-start">
                <label className="form-label">Editora</label>
                <select
                    className="form-select"
                    id="editora"
                    value={codEditora}
                    onChange={(e) => setCodEditora(parseInt(e.target.value))}
                >
                    <option value={1}>Alta Books</option>
                    <option value={2}>Pearson</option>
                    <option value={3}>Novatec Editora</option>
                </select>
            </div>
            <div className="mb-3">
                <label className="form-label">Autores (1 por linha)</label>
                <textarea
                    className="form-control"
                    id="autores"
                    value={autores}
                    onChange={(event) => setAutores(event.target.value)}
                />
            </div>

            <button type="submit" onClick={incluir} className="btn btn-primary">
                Incluir
            </button>
        </div>
    );
}

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],
})
export class LivroDadosComponent implements OnInit {
  livro: Livro;
  autoresForm: string = '';
  editoras: Editora[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private controleLivrosService: ControleLivrosService,
    private router: Router
  ) {
    this.livro = new Livro('', 0, '', '', []);
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir(): void {
    const livro = this.livro;
    this.controleLivrosService.incluir(livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  }
}

<main class="container">
    <h2>Incluir Livro</h2>
    <form (submit)="incluir()" ngNativeValidate>
        <div class="form-group">
            <label for="titulo">Título</label>
            <input type="text" id="titulo" class="form-control" required [(ngModel)]="livro.titulo" name="titulo">
        </div>

        <div class="form-group">
            <label for="resumo">Resumo</label>
            <textarea id="resumo" class="form-control" rows="4" [(ngModel)]="livro.resumo" name="resumo"></textarea>
        </div>

        <div class="form-group">
            <label for="editora">Editora</label>
            <select id="editora" class="form-control" required [(ngModel)]="livro.codEditora" name="editora">
                <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
            </select>
        </div>

        <div class="form-group">
            <label for="autores">Autores (1 por linha)</label>
            <textarea id="autores" class="form-control" rows="4" [(ngModel)]="autoresForm" name="autores"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>
</main>
